name: "Compliance"

on:
  # For Branch-Protection check. Only the default branch is supported. See
  # https://github.com/ossf/scorecard/blob/main/docs/checks.md#branch-protection
  branch_protection_rule:
  # To guarantee Maintained check is occasionally updated. See
  # https://github.com/ossf/scorecard/blob/main/docs/checks.md#maintained
  schedule:
    - cron: '0 0 * * 1'
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  scorecard:
    uses: inigomarquinez/inigomarquinez/.github/workflows/scorecard.yml@main
